# Only used in development
version: "3.1"
services:
  mongo:
    image: mongo
    command: mongod --auth
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Pjjnu8PG78aWLZcJKDHdPnc9xwbjwvZU
      MONGO_INITDB_DATABASE: users
